// <auto-generated />
using FC_Imobiliaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FC_Imobiliaria.Migrations
{
    [DbContext(typeof(ImobiliariaContext))]
    [Migration("20250816005431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FC_Imobiliaria.Models.Imoveis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Definicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroQuartos")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("FC_Imobiliaria.Models.Inquilino", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantImoveis")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Inquilinos");
                });

            modelBuilder.Entity("FC_Imobiliaria.Models.InquilinoImoveis", b =>
                {
                    b.Property<int>("InquilinoID")
                        .HasColumnType("int");

                    b.Property<int>("ImovelID")
                        .HasColumnType("int");

                    b.HasKey("InquilinoID", "ImovelID");

                    b.HasIndex("ImovelID");

                    b.ToTable("InquilinoImoveis");
                });

            modelBuilder.Entity("FC_Imobiliaria.Models.InquilinoImoveis", b =>
                {
                    b.HasOne("FC_Imobiliaria.Models.Imoveis", "Imoveis")
                        .WithMany()
                        .HasForeignKey("ImovelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FC_Imobiliaria.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("InquilinoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imoveis");

                    b.Navigation("Inquilino");
                });
#pragma warning restore 612, 618
        }
    }
}
